sudo: false
language: node_js
node_js:
- '0.12'
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm i -g npm@^2.0.0
before_install:
  - mkdir travis-phantomjs
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH
install:
  - npm install -g bower
  - npm install
  - bower install
script:
  - npm test
after_success:
  - npm run semantic-release && npm run deploy -- --environment=production
